/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/subjects/$slug',
  path: '/subjects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/notes/$id': typeof NotesIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/notes/$id': typeof NotesIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/notes/$id': typeof NotesIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/browse'
    | '/contact'
    | '/login'
    | '/register'
    | '/upload'
    | '/dashboard'
    | '/blog/$slug'
    | '/notes/$id'
    | '/subjects/$slug'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/browse'
    | '/contact'
    | '/login'
    | '/register'
    | '/upload'
    | '/dashboard'
    | '/blog/$slug'
    | '/notes/$id'
    | '/subjects/$slug'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/browse'
    | '/contact'
    | '/login'
    | '/register'
    | '/upload'
    | '/_authenticated/dashboard'
    | '/blog_/$slug'
    | '/notes/$id'
    | '/subjects/$slug'
    | '/_authenticated/admin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UploadRoute: typeof UploadRoute
  BlogSlugRoute: typeof BlogSlugRoute
  NotesIdRoute: typeof NotesIdRoute
  SubjectsSlugRoute: typeof SubjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/subjects/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UploadRoute: UploadRoute,
  BlogSlugRoute: BlogSlugRoute,
  NotesIdRoute: NotesIdRoute,
  SubjectsSlugRoute: SubjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
